- rest-request.go
This PR allows for optionally passing `username:password` in place of an API key in the constructor.
> allow for basic auth

- panel.go
This field required for grafana 4
> Add "RawQuery" field to the "Target" struct

- rest-datasource.go
**Get a single data source by Name**
`GET /api/datasources/name/:name`
Example Request:
```
GET /api/datasources/name/test_datasource HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJrIjoiT0tTcG1pUlY2RnVKZTFVaDFsNFZXdE9ZWmNrMkZYbk
```
**Delete an existing data source by name**
`DELETE /api/datasources/name/:datasourceName`
Example Request:
```
DELETE /api/datasources/name/test_datasource HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJrIjoiT0tTcG1pUlY2RnVKZTFVaDFsNFZXdE9ZWmNrMkZYbk
```
> Add missing functions to GET and DELETE datasources by name

- org.go
- rest-org.go
This PR adds additional implementation for managing organizations and their membership, as well as updating the `OrgUser` structure to represent the format returned by Grafana.
> Additional Organization Implementation

- panel.go
Missed this in the previous grafana 5 pr.
> Adding alias for style definition

- custom-types.go
- panel.go
- change data type of `Gauge.MaxValue` and `Gauge.MinValue` to supports decimal number
- change data type of `Axis.Max` and `Axis.Min` to supports value like `1e10`
- change data type of `Panel.MaxDataPoints` from `int` to `IntString`
> Change data type

- rest-org.go
Utilize `GET /api/orgs` endpoint to get the list of all organizations.
> Support getting all organizations

- .travis.yml
- rest-alertnotification_integration_test.go
An initial attempt at adding integration tests with an actual Grafana instance that is spun-up using the `docker` service.
> alertnotification: initial attempt at integration tests

- helpers_test.go
- rest-alertnotification_integration_test.go
- rest-datasource_integration_test.go
* Move test helpers into a separate file
* Add datasource API CRUD tests
* Move the alertnotification tests into a separate package like the others
> Add datasource integration tests, refactor

- rest-user_integration_test.go
Add integration tests for REST User operations.
> integration: user: add

- rest-org_integration_test.go
> rest: org: add initial integration tests

- README.md
- cmd/backup-dashboards/main.go
- helpers_test.go
- rest-admin_integration_test.go
- rest-alertnotification_integration_test.go
- rest-annotation_integration_test.go
- rest-annotation_test.go
- rest-dashboard.go
- rest-dashboard_integration_test.go
- rest-datasource_integration_test.go
- rest-org_integration_test.go
- rest-user_integration_test.go
All details in the commit messages.
> Fix GetDashboard API mess, update README

- folder.go
- rest-folder.go
- rest-folder_integration_test.go
> Add Folder API support

- .travis.yml
- README.md
- board.go
- cmd/backup-dashboards/main.go
- cmd/backup-datasources/main.go
- cmd/import-dashboards/main.go
- cmd/import-datasources/main.go
- custom-types.go
- panel.go
- panel_test.go
- rest-alertnotification.go
- rest-dashboard.go
- rest-dashboard_integration_test.go
* Run `golangci-lint` to get lots of extra linters and checks
* Add `6.7.1` Grafana
* Add `1.14.x` support
Closes #76.
> Improve CI

- panel.go
- panel_test.go
Hi!
In this PR, I add support for Stackdriver targets.
> Add support for Stackdriver targets

- panel.go
Just working through requests for change in #80 to try and get this stuff implemented.  😄
> pt2: Add RowPanel.Collapsed, Axis.Decimals, ColumnStyle.MappingType, ColumnStyle.ValueMaps

- panel.go
- Add fields to Target struct to support PostgreSQL 
Closes #92
> Add support for PostgreSQL

- README.md
Added Grizzly CLI for Grafana dashboard
> Added Grizzly CLI for Grafana dashboard

- panel.go
Hi!
In this PR, I add support for Heatmap panels: https://grafana.com/docs/grafana/v6.7/getting-started/intro-histograms/#heatmaps
They're available since v6.7 at least (not sure about prior versions)
> Add support for Heatmap panels

- org.go
> use userId json tag instead of id

- README.md
Without setting the time range, grafana dashboard creation would fail
> Adding time range to the example

- panel.go
Hej!
In this PR, I add some of the missing fields in the `SeriesOverride` struct.
> Add some of the missing SeriesOverride fields

- rest-dashboard.go
- rest-dashboard_integration_test.go
- testdata/empty-dashboard-with-uid-2.6.json
- testdata/new-empty-dashboard-2.6.json
This builds on PR #87 I'm not sure how to run the integration tests locally but this should work as expected.  If you need any additional testing please let me know.
Just trying to address the required comments to get this merged in.
> Deleting Dashboard by UID

- README.md
- rest-snapshot.go
- rest-snapshot_integration_test.go
- snapshot.go
Signed-off-by: Julien Pivotto <roidelapluie@inuits.eu>
> Add partial snapshot support

- rest-request.go
Signed-off-by: Pulak Kanti Bhowmick <pkbhowmick007@gmail.com>
Fixed https://github.com/grafana-tools/sdk/issues/154
> Handle URL parse error

- docker-compose.yml
ChangeLog:
- Adding a docker compose file.
- Fixing compile error on unit tests
- Fixing examples import/export of dashboards and datasources.
> Adding docker compose helper.

- panel.go
- panel_test.go
> Fix custom Panel JSON marshalling

- panel.go
As titled. Lets you have data links on series. Example: https://github.com/sourcegraph/sourcegraph/pull/24920/files#diff-4132060621aa0b48b1ada84cd9c0fc0984c98250bfce3fe78d4f15eb5d8b39f6R175-R179
> Add FieldConfig.Links, add FieldConfig to GraphPanel

- rest-team.go
- rest-team_integration_test.go
- team.go
Added support for all endpoints and operations for the TEAM resources
[https://grafana.com/docs/grafana/latest/http_api/team/](https://grafana.com/docs/grafana/latest/http_api/team/)
> Added team REST

- datasource.go
- rest-datasource_integration_test.go
Adding additional datasource fields to match: https://grafana.com/docs/grafana/latest/http_api/data_source/
> Update datasource with additional fields

- rest-admin.go
- rest-admin_integration_test.go
- user.go
1.fix the admin permission doc
2.add change user password interface
> user password
